name: nhm
channels:
  - conda-forge
  - nodefaults
dependencies:
  - folium==0.18
  - ipyleaflet==0.19.2
  - jupyter_contrib_nbextensions
  - jupytext
  - plotly==5.24.1
  - pywatershed>=2.0.1
  - tobler==0.12.0
  - pip:
      - hydroeval==0.1
      - jupyter_black
      - git+https://github.com/paknorton/pyPRMS.git@development
